receivers:
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          static_configs:
            - targets: ['localhost:8888']  # Collector 자체 메트릭
        - job_name: 'node'
          static_configs:
            - targets: ['localhost:9100']  # node_exporter 대상

exporters:
  otlp:
    endpoint: "otel-collector.bocopile.io:4317"
    tls:
      insecure: true  # HTTPS 아닌 경우 true (실습용)

processors:
  batch:

service:
  pipelines:
    metrics:
      receivers: [prometheus]
      processors: [batch]
      exporters: [otlp]
